/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p38-gf512b381
 *
 * Project: 'viewfinder.release+DevKit-E8-HE' 
 * Target:  'release+DevKit-E8-HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::BSP:External peripherals:CAMERA Sensor OV5675@2.2.0 */
#define RTE_Drivers_CAMERA_SENSOR_OV5675           /* Driver CAMERA Sensor */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@2.2.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL    /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::CMSIS Driver:I2C@2.2.0 */
#define RTE_Drivers_I2C              /* Driver I2C */
/* AlifSemiconductor::CMSIS Driver:USART@2.2.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:CDC@2.2.0 */
#define RTE_Drivers_CDC200                 /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:CPI@2.2.0 */
#define RTE_Drivers_CPI              /* Driver CAMERA Controller */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.2.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:ISP@2.2.0 */
#define RTE_Drivers_ISP              /* Driver ISP Controller */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@2.2.0 */
#define RTE_Drivers_MIPI_CSI2              /* Driver MIPI CSI2 */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@2.2.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@2.2.0 */
#define RTE_Drivers_MIPI_DSI               /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.2.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Graphics:Acceleration:Dave2d@1.0.0 */
/*! \brief enable Dave2D acceleration */
#define AIPL_DAVE2D_ACCELERATION


#endif /* RTE_COMPONENTS_H */
